<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

        <Version>0.1.0</Version>
        <RootNamespace>TerritoryClient</RootNamespace>

        <AssemblyName>TushonkaTerritories</AssemblyName>
        <OutputPath>bin\$(Configuration)\$(SolutionName)\$(AssemblyName)\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="cp -a $(TargetPath) $(SolutionDir)../../BepInEx/plugins/$(SolutionName)/" />
        <Exec Command="cp -a $(TargetDir)/Bundles $(SolutionDir)../../BepInEx/plugins/$(SolutionName)/" />
        <Exec Command="cp -a $(TargetPath) $(SolutionDir)release/BepInEx/plugins/$(SolutionName)/" />
        <Exec Command="cp -a $(TargetDir)/Bundles $(SolutionDir)release/BepInEx/plugins/$(SolutionName)/" />
    </Target>
    
    <ItemGroup>
        <None Update="Bundles\ttbundle.bundle">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="PhysicsModule" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.PhysicsModule.dll" />
        <Reference Include="0Harmony" HintPath="..\..\..\BepInEx\core\0Harmony.dll" />
        <Reference Include="spt-common" HintPath="..\..\..\BepInEx\plugins\spt\spt-common.dll" />
        <Reference Include="spt-custom" HintPath="..\..\..\BepInEx\plugins\spt\spt-custom.dll" />
        <Reference Include="spt-reflection" HintPath="..\..\..\BepInEx\plugins\spt\spt-reflection.dll" />
        <Reference Include="Assembly-CSharp" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll" />
        <Reference Include="BepInEx" HintPath="..\..\..\BepInEx\core\BepInEx.dll" />
        <Reference Include="Comfort" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\Comfort.dll" />
        <Reference Include="Comfort.Unity" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\Comfort.Unity.dll" />
        <Reference Include="Newtonsoft.Json" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll" />
        <Reference Include="Sirenix.Serialization" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll" />
        <Reference Include="System" />
        <Reference Include="System.Core" />
        <Reference Include="System.Xml.Linq" />
        <Reference Include="System.Data.DataSetExtensions" />
        <Reference Include="Microsoft.CSharp" />
        <Reference Include="System.Data" />
        <Reference Include="System.Net.Http" />
        <Reference Include="System.Xml" />
        <Reference Include="Unity.TextMeshPro" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll" />
        <Reference Include="UnityEngine" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.dll" />
        <Reference Include="UnityEngine.AssetBundleModule" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.AssetBundleModule.dll" />
        <Reference Include="UnityEngine.CoreModule" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll" />
        <Reference Include="UnityEngine.IMGUIModule" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.IMGUIModule.dll" />
        <Reference Include="UnityEngine.InputLegacyModule" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll" />
        <Reference Include="UnityEngine.TextRenderingModule" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.TextRenderingModule.dll" />
        <Reference Include="UnityEngine.UI" HintPath="..\..\..\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="External\" />
    </ItemGroup>

</Project>